server {
    listen 8080;
    server_name localhost;
    client_max_body_size 200000000;
    root www;
    index index.html;
    error_page 404 /404.html;

    location / {
        allow_methods GET;
        autoindex on;
        root www;
        index index.html;
        cgi_ext .bla;
        cgi_path ./cgi_tester;
    }

    location /google {
        allow_methods GET;
        return 302 https://www.google.com;
    }

    location /cgi-bin/ {
        allow_methods GET POST;
        root www/cgi-bin;
        cgi_ext .py;
        cgi_path /usr/bin/python3;
    }

    location /directory/ {
        allow_methods GET POST;
        root YoupiBanane;
        index youpi.bad_extension;
        cgi_ext .bla;
        cgi_path ./cgi_tester;
    }

    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
        root www;
    }

    location /uploads/ {
        allow_methods GET POST DELETE;
        root www/uploads;
        upload_store www/uploads;
        autoindex on;
    }
}

server {
    listen 8081;
    server_name localhost;
    client_max_body_size 100000000;
    root www;
    index index.html;
    error_page 404 /404.html;

    location / {
        allow_methods GET;
        autoindex on;
        root www;
        index index.html;
    }

    location /files {
        allow_methods GET POST;
        root www;
        autoindex on;
    }
}
