#!/usr/bin/env python3
import os

print("Status: 200 OK\r")
print("Content-Type: text/html\r")
print("\r")

print("<html><body>")
print("<h1>Hello from CGI!</h1>")
print("<p>This is a dynamic response generated by a Python script.</p>")
print("<p><strong>Request Method:</strong>", os.environ.get("REQUEST_METHOD", "Unknown"), "</p>")
print("</body></html>")
